Update audit_report.py
sujayvadlakonda/WeAreTheAdvisors pull request #51
Opened 2023-04-27 23:25 UTC by AkeAmadi

2023-04-28 08:49 UTC, LisaBChen commented
ok, I tested your code, and it only prints out this: 
<img width="816" alt="image" src="https://user-images.githubusercontent.com/55895555/235101100-ce572004-249f-4d74-9977-bbcb2c4c11f3.png">
Could you send me a screenshot of what you got when you tested this?

2023-04-28 08:52 UTC, LisaBChen commented
and when I directly tested your method in audit_report.py , it just resulted in this, instead of an actual gpa number: 
<img width="818" alt="image" src="https://user-images.githubusercontent.com/55895555/235101856-a766d960-7bc7-4a0b-aafb-02a27b8ecaf0.png">

2023-04-28 09:40 UTC, LisaBChen commented
If it's easier on you, for the "core gpa" row, "elective gpa" row, and "combined gpa" row (not the "outstanding requirements" section), in the audit report word doc, you can just have the functions ``` get_core_gpa_section(), get_elective_gpa_section(), and get_combined_gpa_section() ``` return a float instead of a string. I can just access those functions individually, and assign them to separate variables. In addition, I can just have the bolded text labels for those 3 rows (for example " **Core GPA: ** ", " **Elective GPA: ** ", and " ** Combined GPA: ** ") be handled separately from your code. 
<img width="378" alt="image" src="https://user-images.githubusercontent.com/55895555/235112965-1ec5cc9b-f9ec-49e9-807d-2fca82c21eab.png">

2023-04-28 13:57 UTC, sujayvadlakonda requested changes

2023-04-28 13:57 UTC, sujayvadlakonda commented on audit_report.py
> +	    core_gpa = str(self.get_core_gpa)
The error that Lisa is getting is occurring bc line 31 should be 
```
core_gpa = str(self.get_core_gpa())
```
Fix these everywhere

2023-05-04 21:12 UTC, LisaBChen commented
You're using the outdated version of both our branches code.

2023-05-05 22:55 UTC, LisaBChen commented
just letting you know know that I'm uploading your additions to the code for you.

2023-05-07 06:31 UTC, LisaBChen commented
akelanda, did you upload your latest changes, to the outstanding requirements related code, to any of the branches yet? Because your outstanding requirements code still has that bug/error we mentioned before.

2023-05-07 06:36 UTC, LisaBChen requested changes
Where are the changes you made to fix the outstanding requirements section error in your code? Because I remember you saying before that you don't upload your latest code to the github repo.

2023-05-07 18:47 UTC, closed without merging

2023-05-07 19:31 UTC, LisaBChen commented
akelanda, your code for the outstanding requirements section of the audit, still have compilation errors in it etc for some of the transcripts, and it's causing bugs for the rest of program.